FROM public.ecr.aws/genialis/resolwebio/common:4.2.0

LABEL maintainer="Resolwe Bioinformatics authors https://github.com/genialis/resolwe-bio"

# Additional files:
COPY assets/ /opt/resolwebio/assets/
