FROM public.ecr.aws/genialis/resolwebio/base:ubuntu-20.04-03042021

MAINTAINER Resolwe Bioinformatics authors https://github.com/genialis/resolwe-bio

# Force matplotlib backend to a headless one.
ENV MPLBACKEND Agg

# Additional files:
COPY assets/ /opt/resolwebio/assets/
