FROM public.ecr.aws/genialis/resolwebio/base:ubuntu-22.04-14112023

LABEL maintainer="Resolwe Bioinformatics authors https://github.com/genialis/resolwe-bio"

RUN ln -s /usr/bin/python3 /usr/bin/python
